### ISSUE TITLE
non-empty 3D or 4D Problem

### ISSUE THREAD

**Issue by Yiling-Ma** [ShenZheng2000/MATH_32_HW2#1]
![221687678414_ pic](https://github.com/ShenZheng2000/MATH_32_HW2/assets/102650983/96319746-76ba-4bba-aa44-62daa77e11f2)
When I run the $ bash run.sh, I always meet the run time error "non-empty 3D or 4D (batch mode) tensor expected for input. I don't know why. When I tried to print the shape of images, I checked it is 4D.
torch.Size([1, 3, 166, 128])
Sequential(
  (0): Normalization()
  (conv_0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (relu_1): ReLU()
  (conv_1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)

**Comment by ShenZheng2000** [comment]
Could you please clarify which variables you're printing that yield the output: 
```
torch.Size([1, 3, 166, 128]) Sequential(
(0): Normalization()
(conv_0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
(relu_1): ReLU()
(conv_1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)
```

Have you made any alterations to the `run.py`? 

Note that you are supposed to only change `style_and_content.py`.

**Comment by Yiling-Ma** [comment]
<img width="516" alt="Screenshot 2023-06-25 at 20 48 45" src="https://github.com/ShenZheng2000/MATH_32_HW2/assets/102650983/3a89d055-2a8e-43a2-aaeb-f429e2fcfb18">
Yes, I just modified the style_and_content.py. 
I just added `print(style_img.shape)
                       print(model)` to the run.py.
