### ISSUE TITLE
For UserWarning: 

### ISSUE THREAD

**Issue by w-WYmm** [ShenZheng2000/MATH_32_HW2#2]
I am confused about that there are many userwarning.... How can I solve it?
` D:\myAnaconda\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
D:\myAnaconda\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG19_Weights.IMAGENET1K_V1`. You can also use `weights=VGG19_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Performing Style Transfer from content image initialization
Building the style transfer model..
==============Optimizing==============>
`

**Comment by w-WYmm** [comment]
It seems that we need to add a weight parameter to solve it?

**Comment by ShenZheng2000** [comment]
Based on the warnings you've received, it appears that there may be compatibility issues between your version of torch and torchvision. However, for this particular homework assignment, you don't necessarily need to utilize torchvision. 

You have a few options to address the warning: you can choose to ignore it, implement some code to suppress the warning, or uninstall torchvision.
