### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by weixunxie** [ShenZheng2000/MATH_32_HW2#5]
I meet some problems. I can't run "bash run.sh" in the terminal successfully. Is there something I didn't download? 
<img width="1212" alt="截屏2023-07-07 01 30 38" src="https://github.com/ShenZheng2000/MATH_32_HW2/assets/130762808/2e9fa214-34e9-4613-9ff1-bc54ec01144c">

**Comment by ShenZheng2000** [comment]
Your code implementation for `style_and_content.py` is incorrect. Please use print statement in python to check where you are mixing the data type torch tensor and python tuple.

**Comment by weixunxie** [comment]
I fixed that problem. But I met "User Warning". What should I do? Thanks!

<img width="1026" alt="截屏2023-07-07 10 56 52" src="https://github.com/ShenZheng2000/MATH_32_HW2/assets/130762808/77e46132-94dd-4075-9058-cf4e20ee56e5">

**Comment by ShenZheng2000** [comment]
The user warning arises from minor version incompatibility concerns, but it will not have any impact on the resulting image you obtain. You have the option to disregard the warning or implement code to suppress it.
